# Generated by Django 3.1.1 on 2020-09-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task')),
                ('content', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
